class InvoicePdf < Prawn::Document
  def render(invoice)
    @invoice = invoice
    user = invoice.project.user
    client = invoice.project.client
    
    deliverable_details
    move_down 40
    text "Generated by Freely | contact: #{user.email}", align: :center
    super()
  end
  
  def render_header
    
  end
  
  def deliverable_details
    move_down 40
    table invoice_item_rows, :width => 500 do
      row(0).font_style = :bold
      columns(1..3).align = :right
      self.header = true
      self.column_widths = {0 => 325, 1 => 75, 2 => 50, 3 => 50}
    end
  end
  
  
  def invoice_item_rows
    total_price = 0
    [["Description", "Quantity", "Rate", "Total"]] +
    @invoice.deliverables.map do |deliverable|
      quantity = deliverable.count_by_invoice(@invoice)
      price = quantity * deliverable.hourly
      total_price += price
      
      ["#{deliverable.name} ",
            quantity,
            "#{deliverable.hourly}  ",
            "#{price}"]
    end + [[nil, nil, "TOTAL:", total_price]]

  end
end