class InvoicePdf < Prawn::Document
  def render(invoice)
    @invoice = invoice
    
    invoice_details
    user_contact
    client_contact
    
    deliverable_details
    
    footer

    super()
  end
  
  def client_contact
    client = @invoice.project.client
    move_down 20
    text "Invoice to:", style: :bold
    text client.name
    text client.company
    text client.phone if client.phone
    text client.email if client.email
  end
  
  def deliverable_details
    move_down 40
    table invoice_item_rows, :width => 520, position: :center do
      row(0).font_style = :bold
      row(-1).font_style = :bold
      columns(1..3).align = :right
      self.header = true
      self.column_widths = {0 => 325, 1 => 75, 2 => 60, 3 => 60}
    end
  end
  
  def footer 
    bounding_box([bounds.left, bounds.bottom], :width => 550, :height => 20) do
      text "Generated by Freely", align: :center
    end
  end
  
  def invoice_details

    text_box "Invoice No. #{@invoice.number}
      #{Date.today}", align: :right

  end
  
  def invoice_item_rows
    total_price = 0
    [["Description", "Hours", "Rate", "Total"]] +
    @invoice.deliverables.map do |deliverable|
      quantity = deliverable.count_by_invoice(@invoice)
      price = quantity * deliverable.hourly
      total_price += price
      
      ["#{deliverable.name} ",
            quantity,
            "$#{deliverable.hourly}/hr ",
            "$#{price}"]
    end + [[nil, nil, "Amt Due", "$#{total_price}"]]

  end
  
  def render_header
    
  end
  
  def user_contact
    address = @invoice.user_address
    user = @invoice.project.user
    
    text "Invoice from:", style: :bold
    if address
      text address.name
      text address.company_name if address.company_name
      text address.street_1
      text address.street_2 if address.street_2
      text address.city + ", " + address.state + ' ' + address.zip
      text user.email
      # text user.phone
    end
  end
end